name: CI/CD Node-React Deployment

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:  

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build-react || echo "No build script found, skipping" #using custom script instead of default one

      - name: Run tests
        run: npm test || echo "Tests failed"

      - name: Lint code
        run: npx eslint . || echo "Lint warnings/errors detected"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          passphrase: ${{ secrets.EC2_KEY_PASSPHRASE }} 
          port: 22
          debug: true                                    
          script: |
            mkdir -p ~/projects/Devops_Assignment3
            cd ~/projects/Devops_Assignment3
            git pull origin main || git clone git@github.com:Ahmad-009/Devops-Assignment3.git .
            npm install
            npm run build-react || echo "No build script found"
            pm2 restart all || pm2 start npm --name "Devops_Assignment3" -- run start

      - name: Notify on success
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          from: ${{ secrets.EMAIL_USER }}             
          subject: "Deployment Success"
          body: "Your changes have been deployed to QA at http://${{ secrets.EC2_IP }}"
          to: ${{ secrets.QA_EMAIL }}

      - name: Notify on failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          from: ${{ secrets.EMAIL_USER }}               
          subject: "Deployment Failed"
          body: "Workflow failed for PR by ${{ github.actor }}"
          to: ${{ secrets.EMAIL_TO }}
